version: '3'

services:
  app:
    restart: always
    image: "${HOOD_CLIENT_IMAGE}"
    command: >
      sh -c "python3 client.py"
    env_file:
      - ./.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"