version: '3'

services:
  app:
    restart: always
    image: "${HOOD_CLIENT_IMAGE}"
    command: >
      ./infinite_loop.sh
    env_file:
      - ./.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"